# !/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
@Author   ：jiamid
@Time     ：2021/11/16 14:26
@File     ：offile_contents.py
@Software ：PyCharm
"""
offile_contents_special = [
    'container pt-5 not_found',
    'Not Found.',
    '<strong>File Not Found</strong>',
    'File has been removed',
    'The file you were looking for could not be found, sorry for any inconvenience',
    'video_not_found.jpg'
]

offile_contents = [
    'Die Datei befindet sich leider nicht (mehr) auf unseren Servern.',  # http://filestore.to/?d=CD02PDD2Q0
    'No Signal 404 Error Page',
    'Sorry, something went wrong!',
    '410 Gone',
    'Blocked by gogoplay1.com',
    'This file has been removed due to infringement of copyright.',
    'This file is not available anymore!',
    'Streamtape - Error ',
    'File doesn\'t exist',
    'files/error.jpg',
    'File has been removed or does not exist!',
    u'Tento soubor již není dostupný',
    'File does not exist or has been deleted',
    'Unknown column',
    'URL=/notice.php',
    'This video was deleted by it\'s owner.',
    'Oops!',
    'Video not found!',
    'File unavailavle',
    'File not exist or has been removed!',
    'Error. The video was deleted.',
    'Video not found -',
    'Page not found.',
    'The requested ressource does not exist',
    'This video, it has been removed due to copyright issues',
    'was not found on this server.',
    "Sorry, there's no file here with that URL",
    'Video is currently being encoded, try back later.',
    'The file you are trying to download is no longer available.',
    'The file is no longer available.',
    'File is no longer available as it expired or has been deleted.',
    '404 Page not found',
    'The page is currently unavailable or does not exist.',
    'NOT_FOUND',
    "We can't find the video you are looking for.",
    'THE FILE YOU REQUESTED DOES NOT EXIST',
    'This file is no longer available',
    'SQLSTATE[HY000]: General error: 1300',
    'SQLSTATE[42000]: Syntax error or access violation',
    "The page you were looking for doesn't exist",
    'Oops! Page Not Be Found',
    '404 Video not found or has been removed',
    u'Sorry, there’s no such page',
    'This file has been removed due to inactivity',
    'The file you were looking for could not be found, sorry for any inconvenience',
    'The file was deleted by administration because it',
    'Looks like we lost one',
    'was not found on this server',
    'File was not found. It could possibly be deleted',
    'Invalid Download Link',
    'The file you were looking for could not be found, sorry for any inconvenience ',
    'File not found',
    'Nothing found here',
    'This file has been removed due to',
    'The requested file has been deleted',
    'Sorry, content not found.',
    'Page Not Found',
    "The page you're looking for can't be found.",
    'File Not Found',
    'Not Found',
    'The file was deleted by administration',
    'The file you were looking for could not be found',
    'alt="404 File not found!"',
    'File was deleted',
    'Video not available!',
    'File Does not Exist, or Has Been Removed',
    'File is no longer available',
    'NO LONGER AVAILABLE!',
    "We can't find the video you are looking for.",
    "We can't find the file you are looking for.",
    'Sorry this video is unavailable: DMCA Takedown',
    '<h1>Page not found<br />',
    'The video you are looking for is no longer available.',
    'The file was deleted by',
    'this video is not available',
    'File you are looking for is not found.',
    'removed due a copyright violation',
    '404. PAGE NOT FOUND',
    'File is no longer available as it expired or has been deleted',
    '</i>&nbsp;File is not publicly available.</li></ul>',
    '"status":"error"',
    '</i>&nbsp;File has been removed due to inactivity.</li>',
    'Uh, Oh!</strong> This file does not exist',
    'Sorry this video does not exist',
    'class="err">Video not found',
    'The requested file has been deleted for inactivity',
    'File does not exist on this server',
    'File not exist!',
    '<br>Conversion stage:',  # https://vidfast.co/6g4x8nogkto2
    '/embed/novideo.mp4',  # https://www.yourupload.com/watch/avSuSfwR3w20
    'Dosya bulunmamaktad',  # http://dunyavid.com/5735937.video
    u'Stránka nenalezena',  # https://ulozto.cz/file/c8HksHHJ1
    'The file was removed by administrator',
    u'URL ไม่ถูกต้อง ลองค้นหาดูใหม่อีกครั้ง',
    'Nie znaleziono pliku',
    u'Xin lỗi Bạn, file này không còn tồn tại',
    'The file you have requested does not exist or has been removed',
    'Brak pliku !!!',
    u'Törölt videó',
    'This file does not exist',
    u'Az adott fájl nem létezik',
    '|small3|videojs7',  # https://gounlimited.to/bvi1li8k0fyr.html
    '<iframe src="/e/"'  # https://dood.to/d/m2kpiqf9ztqpvhn6sv8sq5n1rxuafx9
]
